plugins {
    id 'com.android.application'
    id 'kotlin-android'
    id 'kotlin-parcelize'
}

android {
    namespace 'com.benoitfreslon.unity.vibrations.plugin'
    compileSdkVersion 33

    defaultConfig {
        applicationId "com.benoitfreslon.unity.vibrations.plugin"
        minSdkVersion 19
        targetSdkVersion 33
        versionCode 1
        versionName "1.0"

        testInstrumentationRunner "androidx.test.runner.AndroidJUnitRunner"
    }

    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
        }
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
    }

    kotlinOptions {
        jvmTarget = '17'
    }
}

dependencies {

    // --- Local modules/libraries ---
    implementation project(path: ':lib')
    implementation fileTree(dir: 'libs', include: ['*.jar'])

    // --- Core ---
    implementation "org.jetbrains.kotlin:kotlin-stdlib-jdk8:$kotlin_version"
    implementation "androidx.appcompat:appcompat:$appcompat_version"
    implementation "androidx.core:core-ktx:$androidXCore_version"
    implementation "androidx.constraintlayout:constraintlayout:$contraintLayout_version"

    // --- Testing ---
    testImplementation "junit:junit:$junit_version"
    androidTestImplementation "androidx.test.ext:junit:$androidXJunit_version"
    androidTestImplementation "androidx.test.espresso:espresso-core:$androidXEspresso_version"
}
