plugins {
    id 'com.android.library'
    id 'kotlin-android'
    id 'kotlin-parcelize'
}

android {
    namespace 'com.benoitfreslon.unity.vibrations.lib'
    compileSdkVersion 33

    sourceSets {
        main {
            manifest.srcFile '../../../Runtime/Plugins/Android/AndroidManifest.xml'
            java.srcDirs = ['../../../Runtime/Plugins/Android/java', 'src/main/java']
            res.srcDirs = ['src/main/res', '../../../Runtime/Plugins/Android/res']
        }
    }

    defaultConfig {
        minSdkVersion 19
        targetSdkVersion 33

        testInstrumentationRunner "androidx.test.runner.AndroidJUnitRunner"
        consumerProguardFiles 'consumer-rules.pro'
    }

    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
        }
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
    }

    kotlinOptions {
        jvmTarget = '17'
    }
}

dependencies {

    // --- Local modules/libraries ---
    implementation fileTree(dir: 'libs', include: ['*.jar'])

    // --- Core ---
    implementation "org.jetbrains.kotlin:kotlin-stdlib-jdk8:$kotlin_version"
    implementation "androidx.appcompat:appcompat:$appcompat_version"
    implementation "androidx.core:core-ktx:$androidXCore_version"

    // --- Testing ---
    testImplementation "junit:junit:$junit_version"
    androidTestImplementation "androidx.test.ext:junit:$androidXJunit_version"
    androidTestImplementation "androidx.test.espresso:espresso-core:$androidXEspresso_version"
}
